name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          sudo apt-get update
          sudo snap install aws-cli --classic
          aws ec2 describe-instances --instance-ids $EC2_INSTANCE_ID
          scp -i ~/.ssh/key.pem -r ./* ec2-user@${{ secrets.EC2_INSTANCE_IP }}:/var/www/html
          ssh -i ~/.ssh/key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'sudo systemctl restart nginx'
